name: Validate Files

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Sample run'
        required: true
        default: 'main'

jobs:
  validate-files:
    runs-on: Ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      
      - run: |
          python .github/workflows/validate-files.py -d
