name: Validate Files

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Sample run'
        required: true
        default: 'main'

jobs:
  validate-files:
    runs-on: Ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml schema

      - uses: actions/checkout@v4
      
      - run: |
          python .github/scripts/validate-files.py -d
